// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnow77oF_hV78lTYJ244i0ATm6HIpCff8',
    appId: '1:1055581450807:web:ccdaa7142d135fbc3605b2',
    messagingSenderId: '1055581450807',
    projectId: 'dropgo-a03cb',
    authDomain: 'dropgo-a03cb.firebaseapp.com',
    storageBucket: 'dropgo-a03cb.firebasestorage.app',
    measurementId: 'G-98F20YNZ5F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaZSnMWp_ReF_-mwoUCVLzouU_iK_kEmE',
    appId: '1:1055581450807:android:48389af17badeb143605b2',
    messagingSenderId: '1055581450807',
    projectId: 'dropgo-a03cb',
    storageBucket: 'dropgo-a03cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlmmU9SI4xWJjL9Q7PkJddQhoO0BiFo7M',
    appId: '1:1055581450807:ios:87cd2592442e8ca13605b2',
    messagingSenderId: '1055581450807',
    projectId: 'dropgo-a03cb',
    storageBucket: 'dropgo-a03cb.firebasestorage.app',
    iosBundleId: 'com.example.dropgo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlmmU9SI4xWJjL9Q7PkJddQhoO0BiFo7M',
    appId: '1:1055581450807:ios:87cd2592442e8ca13605b2',
    messagingSenderId: '1055581450807',
    projectId: 'dropgo-a03cb',
    storageBucket: 'dropgo-a03cb.firebasestorage.app',
    iosBundleId: 'com.example.dropgo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnow77oF_hV78lTYJ244i0ATm6HIpCff8',
    appId: '1:1055581450807:web:9f8cef80e22e0d603605b2',
    messagingSenderId: '1055581450807',
    projectId: 'dropgo-a03cb',
    authDomain: 'dropgo-a03cb.firebaseapp.com',
    storageBucket: 'dropgo-a03cb.firebasestorage.app',
    measurementId: 'G-ZL3YLMNQFR',
  );
}
